/**:
  ros__parameters:
    # Unserpervised Learning Clustering Parameters:
    dist_threshold: 0.1

    # Circle Fitting Parameters:
    min_cluster_size: 3
    min_obstacle_radius: 0.02
    max_obstacle_radius: 0.25

    # Visualization Parameters:
    min_centroid_dist: 0.05 # Minimum distance between centroids to be visualized as separate obstacles