/**:
  ros__parameters:
    # SLAM EKF Parameters:
    slam_process_variance: 0.001
    slam_measurement_variance: 1.0
    slam_obs_radius: 0.038

    # Unserpervised Learning Clustering Parameters:
    dist_threshold: 0.1

    # Circle Fitting Parameters:
    min_cluster_size: 3
    min_obst_radius: 0.02
    max_obst_radius: 0.25