/**:
  ros__parameters:
    laser_max_range: 3.5
    laser_min_range: 0.12
    laser_angle_min: -3.14
    laser_angle_max: 3.14
    laser_angle_increment: 0.01745
    laser_num_readings: 360
    laser_resolution: 0.01745
    laser_scan_variance: 0.0001